import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.scss';
import Navbar from '@/components/navbar/Navbar';

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['100', '300', '500', '700', '900'],
});

export const metadata: Metadata = {
  title: 'Netflix',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className="container">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
